[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pyrogram>=2.0.106",
    "python-telegram-bot>=22.4",
    "requests>=2.32.5",
    "telegram>=0.0.1",
    "tgcrypto>=1.2.5",
]
